package CRUDCARDekho;

import java.awt.Taskbar.State;
import java.io.FileInputStream;

import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Arrays;
import java.util.Properties;

import com.mysql.cj.protocol.Resultset;

public class CarCRUD {
	public Connection openConnection() throws IOException, ClassNotFoundException, SQLException {
		FileInputStream fileInputStream;
		
			fileInputStream = new FileInputStream("dbcondig.properties");
			Properties properties=new Properties();
			properties.load(fileInputStream);
			
			Class.forName(properties.getProperty("className"));
			
			Connection connection=DriverManager.getConnection(properties.getProperty("url2"),properties.getProperty("user"),properties.getProperty("password"));
			
			
		return connection;
		
		
		
	}
	
	public void inserCar(Car car) throws ClassNotFoundException, IOException, SQLException {
	  
		Connection connection=openConnection();
		String query="insert into car values(?,?,?,?,?)";
		
		PreparedStatement preparedStatement=connection.prepareStatement(query);
		
		preparedStatement.setInt(1,car.getId());
		preparedStatement.setString(2, car.getName());
		preparedStatement.setString(3, car.getComponyName());
		preparedStatement.setDouble(4, car.getPrice());
		preparedStatement.setString(5, car.getColor());
		
		int result=preparedStatement.executeUpdate();
		if (result==1) {
			System.out.println("susscessfully insert one car");
		} else {
               System.out.println("failed to insert the car");
               
		}
		connection.close();
		
	
	}
	
	public void updateCar(Car car) throws ClassNotFoundException, IOException, SQLException {
		Connection connection=openConnection();
		String query="update car set name=?,compny_name=?,price=?,color=? where id=?";
		PreparedStatement preparedStatement=connection.prepareStatement(query);
		
		
		preparedStatement.setString(1, car.getName());
		preparedStatement.setString(2, car.getComponyName());
		preparedStatement.setDouble(3, car.getPrice());
		preparedStatement.setString(4, car.getColor());
		preparedStatement.setInt(5,car.getId());
		
		int result=preparedStatement.executeUpdate();
		if (result==1) {
			System.out.println("successfully updated");
			
		} else {
			System.out.println("record not updated");
		}
		
		connection.close();
	

}
	
	public void deleteCar(int id) throws ClassNotFoundException, IOException, SQLException {
		
		Connection connection=openConnection();
		String query="delete from car where id=?";
		PreparedStatement preparedStatement=connection.prepareStatement(query);
		
		preparedStatement.setInt(1, id);
		int result=preparedStatement.executeUpdate();
		
		if (result==1) {
			System.out.println("successfully remove the record of car");
		} else {
			System.out.println("not removed the record ");
		}
		
		
		connection.close();
	}
	
	
	

	
	
	//here i will give static query becouse it is constant so that here i will make use of Statement interface 
	public void showAllCars() throws ClassNotFoundException, IOException, SQLException {
		Connection connection=openConnection();
		String query="select * from car";
		Statement statement=connection.createStatement();
		ResultSet resultSet=statement.executeQuery(query);
		
		//A table of data representing a database result set, whichis usually generated by executing a statement that queries the database. 
		//A ResultSet object maintains a cursor pointing to its current row of data. Initially the cursor is positionedbefore the first row. 

	    while(resultSet.next())	{
	    	System.out.println(resultSet.getInt(1)+"||"+resultSet.getString(2)+"||"+resultSet.getString(3)+"||"+resultSet.getDouble(4)+"||"+resultSet.getString(5));
//	        System.out.println("one");  
	    }	
		connection.close();
		
	}

	public void showCar(int id) throws ClassNotFoundException, IOException, SQLException {
		Connection connection = openConnection();
		String query="select * from car where id=?";
		
		PreparedStatement preparedStatement=connection.prepareStatement(query);
		preparedStatement.setInt(1, id);
		ResultSet result = preparedStatement.executeQuery();
		while (result.next()) {
           System.out.println(result.getInt(1)+"||"+result.getString(2)+"||"+result.getString(3)+"||"+result.getString(5)+"||"+result.getDouble(4)+"\n");
		}
		connection.close();
		
	}
}

